/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** コンテンツ一覧の取得 */
        get: operations["ContentController_getAllContentList"];
        put?: never;
        /** コンテンツの作成 */
        post: operations["ContentController_addContent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** コンテンツの取得 */
        get: operations["ContentController_getContent"];
        /** コンテンツの更新 */
        put: operations["ContentController_updateContent"];
        post?: never;
        /** コンテンツの削除 */
        delete: operations["ContentController_deleteContent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Content: {
            /**
             * @description コンテンツのID
             * @example 1
             */
            id: number;
            /**
             * @description コンテンツのタイトル
             * @example Hello Title
             */
            title: string | null;
            /**
             * @description コンテンツの本文
             * @example Hello Body
             */
            body: string | null;
            /**
             * Format: date-time
             * @description 作成日時
             * @example 2025-04-04T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description 更新日時
             * @example 2025-04-04T00:00:00.000Z
             */
            updatedAt: string;
        };
        CreateContentDTO: {
            /**
             * @description コンテンツのタイトル
             * @example Hello Title
             */
            title: string;
            /**
             * @description コンテンツのボディ
             * @example Hello Body
             */
            body: string;
        };
        UpdateContentDTO: {
            /**
             * @description コンテンツのタイトル
             * @example Update Title
             */
            title: string;
            /**
             * @description コンテンツのボディ
             * @example Update Body
             */
            body: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ContentController_getAllContentList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description コンテンツ一覧を取得します */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Content"][];
                };
            };
        };
    };
    ContentController_addContent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateContentDTO"];
            };
        };
        responses: {
            /** @description 新しいコンテンツが作成されました */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Content"];
                };
            };
        };
    };
    ContentController_getContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 指定されたIDのコンテンツを取得します */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Content"];
                };
            };
        };
    };
    ContentController_updateContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateContentDTO"];
            };
        };
        responses: {
            /** @description コンテンツが更新されました */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Content"];
                };
            };
        };
    };
    ContentController_deleteContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description コンテンツが削除されました */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
